
import React from 'react';

const TermsOfUse = () => {
    // Basic styling for readability
    const styles: { [key: string]: React.CSSProperties } = {
        container: {
            padding: '40px 20px',
            maxWidth: '800px',
            margin: '0 auto',
            fontFamily: 'sans-serif',
            lineHeight: '1.6',
            color: '#333',
        },
        header: {
            borderBottom: '2px solid #eee',
            paddingBottom: '10px',
            marginBottom: '20px',
        },
        section: {
            marginBottom: '30px',
        },
        h1: {
            fontSize: '2.5em',
        },
        h2: {
            fontSize: '1.8em',
            marginTop: '0',
        }
    };

    return (
        <div style={styles.container}>
            <header style={styles.header}>
                <h1 style={styles.h1}>Terms of Use</h1>
            </header>

            <section style={styles.section}>
                <p>Last updated: {new Date().toLocaleDateString()}</p>
                <p>
                    Please read these Terms of Use ("Terms") carefully before using the PROMPT MASTER website (the "Service") operated by us.
                </p>
                <p>
                    Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
                </p>
            </section>

            <section style={styles.section}>
                <h2 style={styles.h2}>1. Accounts</h2>
                <p>
                    When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
                </p>
            </section>

            <section style={styles.section}>
                <h2 style={styles.h2}>2. User-Generated Content and Conduct</h2>
                <p>
                    You are solely responsible for the content you create, input, or generate using our Service ("User Content"). You agree not to use the Service to create, display, or distribute any User Content that:
                </p>
                <ul>
                    <li>Is illegal, fraudulent, or promotes criminal activity.</li>
                    <li>Is defamatory, obscene, pornographic, vulgar, or offensive.</li>
                    <li>Promotes discrimination, bigotry, racism, hatred, harassment, or harm against any individual or group.</li>
                    <li>Is violent or threatening or promotes violence or actions that are threatening to any person or entity.</li>
                    <li>Infringes on any third party's intellectual property rights.</li>
                </ul>
                <p>
                    We reserve the right, but are not obligated, to remove or disable access to any User Content that we believe, in our sole discretion, violates these Terms. We are not responsible or liable for the User Content generated by our users.
                </p>
            </section>

            <section style={styles.section}>
                <h2 style={styles.h2}>3. Intellectual Property</h2>
                <p>
                    The Service and its original content (excluding User Content), features, and functionality are and will remain the exclusive property of PROMPT MASTER and its licensors. The Service is protected by copyright, trademark, and other laws of both the and foreign countries.
                </p>
            </section>
            
            <section style={styles.section}>
                <h2 style={styles.h2}>4. Termination</h2>
                <p>
                    We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                </p>
            </section>

            <section style={styles.section}>
                <h2 style={styles.h2}>5. Limitation Of Liability</h2>
                <p>
                    In no event shall PROMPT MASTER, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
                </p>
            </section>

            <section style={styles.section}>
                <h2 style={styles.h2}>6. Changes To These Terms</h2>
                <p>
                    We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
                </p>
            </section>

            <section style={styles.section}>
                <h2 style={styles.h2}>7. Contact Us</h2>
                <p>
                    If you have any questions about these Terms, please contact us at: [Your Contact Email Address]
                </p>
            </section>
        </div>
    );
};

export default TermsOfUse;
